### ISSUE TITLE
Typo in fp2 dataset's data.json file

### ISSUE THREAD

**Issue by nishikaz** [pfnet-research/japanese-lm-fin-harness#2]
I believe there's a typo in the fp2 dataset's `data.json` file, specifically at this line: [fp2/data.json#L1383](https://github.com/pfnet-research/japanese-lm-fin-harness/blob/970629b9b155c449c1b09e78b3bb82c8567c2b61/jlm_fin_eval/datasets/fp2/data.json#L1383C90-L1383C92)

The typo is in the `context` for choice 3. It currently says 
"３．（ア）８０％2（イ）３３０ｍ（ウ）４００ｍ2（エ）５０％", 
but I believe it should be 
"３．（ア）８０％（イ）３３０ｍ2（ウ）４００ｍ2（エ）５０％".

Here is the original question for you to check: 問57 of [FP2過去問#202105](https://www.jafp.or.jp/exam/mohan/files/g2_202105_q.pdf).

Can you please check and fix this? Thanks!

**Comment by masanorihirano** [comment]
https://github.com/pfnet-research/japanese-lm-fin-harness/pull/4/files

I made a hot fix. Could you check it?
I'll merge it in the next release.

**Comment by nishikaz** [comment]
Thanks for the hot fix branch.
I think an additional edit is required to complement your changes.
I've forked the repo and added a commit to it. Could you take a look at this?
https://github.com/nishikaz/japanese-lm-fin-harness/commit/2aba44da8d5ed769e2fdf8ebd4f4d8f4a342ebb2

I can open a new pull request from my forked branch, or you can add the commit to the hot fix branch yourself. (It seems I'm not allowed to commit directly to the original repo.)

I appreciate your effort in sharing very helpful data with us.

**Comment by masanorihirano** [comment]
Thank you for pointing out. I modified the PR. I apologize for it and thank you for your suggestion again.

**Comment by masanorihirano** [comment]
This PR is now merged.
